apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trivy-pvc
  namespace: trivy-workstation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: trivy-pv

